version: "3.9"
services:
  pub:
    build: .
    image: cheebz/go-pub
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - AUTH=${AUTH}
      - CLIENT=${CLIENT}
      - RSA_PUBLIC_KEY=/etc/rsa/public.pem
      - RSA_PRIVATE_KEY=/etc/rsa/private.pem
      # - SSL_CERT=./certs/cert.pem
      # - SSL_KEY=./certs/key.pem
    env_file:
      - ${ENV}.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${RSA_PUBLIC_KEY}:/etc/rsa/public.pem
      - ${RSA_PRIVATE_KEY}:/etc/rsa/private.pem
    networks:
      - default
      - pub_net
      - auth_net
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # Can this be baked into either image?
      - ./postgres-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} # Can this be made optional?

volumes:
  postgres-data:

networks:
  pub_net:
    driver: bridge
    name: pub_net
  auth_net:
    driver: bridge
    name: auth_net