apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pub-postgres
  labels:
    app: go-pub-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-pub-postgres
  template:
    metadata:
      labels:
        app: go-pub-postgres
    spec:
      containers:
      - name: go-pub-postgres
        image: postgres:latest
        resources: # TODO: Determine eventually
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef:
              name: go-pub-postgres
              key: db_name
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: go-pub-postgres
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: go-pub-postgres
              key: db_password
        volumeMounts:
        - name: go-pub-postgres-data-volume
          mountPath: "/var/lib/postgresql/data/"
        - name: go-pub-postgres-initdb-volume
          mountPath: "/docker-entrypoint-initdb.d/"
      volumes:
        - name: go-pub-postgres-initdb-volume
          confgMap:
            confgMapName: go-pub-postgres-initdb
        - name: go-pub-postgres-data-volume
          persistentVolumeClaim:
            claimName: go-pub-postgres-data
      readinessProbe:
          failureThreshold: 5
          command: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-pub-postgres-service
spec:
  selector:
    app: go-pub-postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432