apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-pub-uploads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      type: uploads